//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_user()
        {
            this.tbl_product = new HashSet<tbl_product>();
        }
    
        public int u_id { get; set; }
        [Required(ErrorMessage = "*Este campo es requerido")]
        public string u_name { get; set; }
        [Required(ErrorMessage = "*Este campo es requerido")]
        [EmailAddress(ErrorMessage = "No es una dirección de correo válida.")]
        public string u_email { get; set; }
        [Required(ErrorMessage = "*Este campo es requerido")]
        public string u_password { get; set; }
        [Required(ErrorMessage = "*Este campo es requerido")]
        public string u_image { get; set; }
        public string u_contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_product> tbl_product { get; set; }
    }
}
